media:
  input: media
  output: /media

content:
  - name: pages
    label: Site Pages
    type: collection
    path: /
    filename: "{slug}.html"
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Body Content
        type: rich-text